#cloud-config
hostname: inserthostname-here
manage_etc_hosts: True
system_info:
  default_user:
    name: cisco
password: cisco
chpasswd: { expire: False }
ssh_pwauth: True
ssh_authorized_keys:
  - your-ssh-pubkey-line-goes-here
timezone: Asia/Tokyo
locale: ja_JP.utf8
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        ethernets:
          ens2:
            addresses:
              - 192.168.100.100/24
            gateway4: 192.168.100.5
            dhcp4: false
            nameservers:
              addresses:
                - 192.168.254.5
        version: 2
runcmd:
  - sudo netplan apply